### Dogs create
POST http://localhost:3000/dogs.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUwMTcwMjl9.1KXN-99UC4cAKTv6vEvNRxr89E-HsNH8onWC5-YkLnU
Content-Type: application/json

{
  "name": "Charles",
  "age": 5,
  "breed": "shiba"
}

### USER CREATE

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}